### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by TahjDev** [nick-barr/PillowCamp#1]
- The format needs to be fixed, just google markdown syntax refer to this MVP LIST https://github.com/appacademy/bluebird/wiki/mvp-list
- Your bonus functionality says "chirps". I dont think you have chirps. 
- I dont really understand what the bonus features are either
- Every MVP should have some kind of timeline, the number of days you'll predict it to take.
- The MVP's should also be in order (disregard heroku being first). Production README should be at the end though
- I also dont see anything about errors in the User Auth MVP

**Comment by TahjDev** [comment]
MVP number 3. Do you need to search to view spots or are you going to render spots automatically based on location?

**Comment by nick-barr** [comment]
Just updated based on comments for MVP #3. They should be able to search by location and couple of pre-defined searches based on common attributes of all spots.
