### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by TahjDev** [nick-barr/PillowCamp#2]
- It might make more sense to store longitude and latitude instead of a specific location cause thats what you're gonna need for google maps api
- I see your question about the other tables. Yea it would be easier to just save it on the spot itself
- I dont see any created_at or updated_at columns?
- all your foreign keys should be indexed for look up times
- You can just use the google search API with the google maps api to help you search by cities?
- I dont think you need the location column on spots

**Comment by nick-barr** [comment]
Hi Tahj,

Hope your holidays were merry :)

This has been updated. Let me know if you have other comments.

Thanks,
Nick
